<a href="https://colab.research.google.com/github/rund-omari/Data.Eng3/blob/main/students/nooralwedyan/solution1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
data=pd.read_csv("https://raw.githubusercontent.com/rund-omari/Data.Eng3/refs/heads/main/datasets/jordan_ecommerce_raw.csv")

In [3]:
data.head()

,order_id,customer_id,city,category,order_amount,quantity,order_date,payment_method,delivery_days,customer_rating
0,ORD-1001,CUS-027,Zarqa,Fashion,52.50,1,2026-06-17,Card,26,NaN
1,ORD-1002,CUS-051,Irbid,Fashion,33.40,2,2026-08-16,CliQ,3,1.0
2,ORD-1003,CUS-076,Aqaba,Fashion,29.50,1,2026-06-12,CliQ,2,3.0
3,ORD-1004,CUS-036,Irbid,Electronics,23.19,2,2026-08-31,Card,1,5.0
4,ORD-1005,CUS-075,Salt,Beauty,84.28,5,2026-05-31,CliQ,1,NaN

In [5]:
data.shape

(413, 10)

In [6]:
data.columns

Index(['order_id', 'customer_id', 'city', 'category', 'order_amount',
       'quantity', 'order_date', 'payment_method', 'delivery_days',
       'customer_rating'],
      dtype='object')

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 413 entries, 0 to 412
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         413 non-null    object
 1   customer_id      413 non-null    object
 2   city             390 non-null    object
 3   category         413 non-null    object
 4   order_amount     396 non-null    float64
 5   quantity         413 non-null    int64
 6   order_date       413 non-null    object
 7   payment_method   400 non-null    object
 8   delivery_days    413 non-null    int64
 9   customer_rating  367 non-null    float64
dtypes: float64(2), int64(2), object(6)
memory usage: 32.4+ KB

In [9]:
data.describe()

       order_amount    quantity  delivery_days  customer_rating
count    396.000000  413.000000     413.000000       367.000000
mean      74.218434    2.970944       2.677966         2.989101
std      270.877718    1.479349       2.809558         1.561102
min      -56.080000   -1.000000       1.000000         1.000000
25%       23.062500    2.000000       1.000000         2.000000
50%       38.240000    3.000000       2.000000         3.000000
75%       65.037500    4.000000       3.000000         4.000000
max     3499.810000    5.000000      26.000000         8.000000

In [10]:
data["city"]

0        Zarqa
1        Irbid
2        Aqaba
3       Irbid
4         Salt
        ...
408      Zarqa
409      Irbid
410      Aqaba
411      Amman
412      Aqaba
Name: city, Length: 413, dtype: object

In [15]:
data[["order_amount","delivery_days"]]

     order_amount  delivery_days
0           52.50             26
1           33.40              3
2           29.50              2
3           23.19              1
4           84.28              1
..            ...            ...
408          9.01              3
409         73.64              2
410          9.93              3
411         39.03              2
412        999.00              2

[413 rows x 2 columns]

In [16]:
data[data["delivery_days"]>3]

,order_id,customer_id,city,category,order_amount,quantity,order_date,payment_method,delivery_days,customer_rating
0,ORD-1001,CUS-027,Zarqa,Fashion,52.50,1,2026-06-17,Card,26,NaN
6,ORD-1007,CUS-043,irbid,Home,144.19,1,2026-03-27,Card,4,NaN
12,ORD-1013,CUS-141,Aqaba,Books,66.58,3,2026-05-18,Card,5,5.0
33,ORD-1034,CUS-136,Salt,Books,NaN,3,2026-07-11,Cash,4,3.0
37,ORD-1038,CUS-053,NaN,Electronics,50.83,1,2026-06-14,CliQ,5,3.0
...,...,...,...,...,...,...,...,...,...,...
384,ORD-1385,CUS-093,Salt,Beauty,127.69,5,2026-09-27,Card,5,1.0
389,ORD-1390,CUS-054,Salt,Books,41.01,4,2026-02-25,Cash,5,2.0
397,ORD-1398,CUS-055,irbid,Electronics,22.47,2,2026-08-03,Cash,6,3.0
399,ORD-1400,CUS-056,Aqaba,Fashion,144.04,4,2026-03-16,Cash,5,3.0
401,ORD-1120,CUS-128,Zarqa,Beauty,40.45,3,2026-07-31,Cash,6,NaN

In [17]:
data[data["city"]=="Amman"]

,order_id,customer_id,city,category,order_amount,quantity,order_date,payment_method,delivery_days,customer_rating
13,ORD-1014,CUS-076,Amman,Electronics,25.56,5,2026-04-14,CliQ,3,3.0
31,ORD-1032,CUS-108,Amman,Electronics,29.31,1,2026-06-08,NaN,2,2.0
34,ORD-1035,CUS-118,Amman,Electronics,17.88,3,2026-01-08,CliQ,1,1.0
43,ORD-1044,CUS-141,Amman,Electronics,24.61,5,2026-03-06,CliQ,6,4.0
56,ORD-1057,CUS-079,Amman,Fashion,39.17,4,2026-06-15,CliQ,2,5.0
...,...,...,...,...,...,...,...,...,...,...
354,ORD-1355,CUS-119,Amman,Home,128.30,5,2026-08-09,Card,5,5.0
357,ORD-1358,CUS-117,Amman,Fashion,56.06,4,2026-04-18,Card,6,5.0
392,ORD-1393,CUS-140,Amman,Fashion,15.39,4,2026-07-21,CliQ,1,5.0
405,ORD-1309,CUS-144,Amman,Books,31.48,4,2026-07-07,Cash,1,4.0
411,ORD-1319,CUS-109,Amman,Electronics,39.03,1,2026-05-31,CliQ,2,8.0

In [ ]:
#The dataset has 413 rows and 10 columns
#The dataset has missing values in some columns
#The dataset has different datatypes